### ISSUE TITLE
Lack of Exit icons in Sign up flow & Exercise flow

### ISSUE THREAD

**Issue by Tara812** [vinsouza99/BodyBuddy#244]
![Screenshot 2024-11-18 at 9 29 51 PM](https://github.com/user-attachments/assets/c9c07d47-3efc-4029-af55-653fb19dfe61)
![Screenshot 2024-11-18 at 9 25 25 PM](https://github.com/user-attachments/assets/cf26e860-ed5e-430a-80c3-b475c97eabcb)

**Comment by yoshan0921** [comment]
@Tara812 Added exit icon on demo screen.

![image](https://github.com/user-attachments/assets/585b13db-285b-409a-8190-72cee0ef095b)
