### ISSUE TITLE
Exit exercise POPUP lack of description text & icon doesnt show

### ISSUE THREAD

**Issue by Tara812** [vinsouza99/BodyBuddy#245]
![Screenshot 2024-11-18 at 9 33 16 PM](https://github.com/user-attachments/assets/317001ca-964f-4a9f-b072-8c540e52296c)
<img width="688" alt="Screenshot 2024-11-18 at 9 33 11 PM" src="https://github.com/user-attachments/assets/9204da0d-cbef-476d-87ed-5d36e3900305">

**Comment by cocoysg** [comment]
@yoshan0921 ok I will look into this tomorrow.

**Comment by vinsouza99** [comment]
I have solved the missing icon issue

**Comment by vinsouza99** [comment]
oops, the buttons still need fixing lol I will reopen
