### ISSUE TITLE
Will we limit time for exercise? 

### ISSUE THREAD

**Issue by Tara812** [vinsouza99/BodyBuddy#246]
Also I think it would be better if the "pause" and "skip" icons are closer to the countdown time as in the design.
![Screenshot 2024-11-18 at 9 30 56 PM](https://github.com/user-attachments/assets/8245399d-66ce-4846-acce-c3b09b3bf2bf)
<img width="377" alt="Screenshot 2024-11-18 at 9 41 34 PM" src="https://github.com/user-attachments/assets/09ccd3f0-c365-4582-8733-4a12526b437d">

**Comment by yoshan0921** [comment]
@Tara812 
My apology, but this page is a too complex for short term development from my current implementation skill and at present it is only possible to manage sets either on a ‘repeat’ basis or on a ‘duration’ basis.

The duration (count down) is zero means that the set is managed on a repetition basis. It is up to the AI whether to manage “set” on a repetition or time basis.
