### ISSUE TITLE
The color of disabled button is too light

### ISSUE THREAD

**Issue by yoshan0921** [vinsouza99/BodyBuddy#285]
![image](https://github.com/user-attachments/assets/0e8a1d38-48ea-43c0-9132-3fdf05c5dcd7)

**Comment by yoshan0921** [comment]
When the specified exercise doesn't respond to motion detection, the practice button is displayed as html's disabled attribution. Could you please help adjust the "disabled background color" in theme.js?

**Comment by cocoysg** [comment]
Thank you Yosuke for highlighting this. I'll work on it.
